%YAML 1.2
---
#app setting

skill:
    name: subtitles
    wrapper: GenerativeResponse

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1

reader:
    wrapper: ReaderSubtitles
    train_data: /home/pzhu/data/dialog/OpenSubtitles/xml/en
    max_seq_len: 50

model:
    device: "cuda:0"
    bert_model_name: "bert-base-uncased"
    encoder_hidden_layers: 5
    encoder_hidden_size: 768
    encoder_intermediate_size: 3072
    encoder_attention_heads: 8
    encoder_freeze: False
    dropout: 0.1
    decoder_hidden_layers: 5
    decoder_attention_heads: 8
    decoder_hidden_size: 3072
    learning_rate: 0.0001
    weight_decay: 0
    momentum: 0.9
    optimizer: "adam"
    epochs: 10000
    batch_size: 30
    num_workers: 1
    saved_model: 'data/cornell/model_subtitles.pt'
    save_per_epoch: 100

reinforcement:
    learning_rate: 0.0001
    maxloop: 20
    discount: 0.95

logger:
    appname: subtitles
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/cornell/train.log

