%YAML 1.2
---

ner:
    tokenizer: spacy

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

model:
    device: "cpu"
    max_seq_len: 10
    max_entity_types: 1024

skills:
    babi:
        wrapper: RuleResponse
        dialogflow: data/babi/babi.xlsx
        w2v_word2idx: data/word2vec/en/bert-base-uncased.lookup 
        w2v_idx2vec: data/word2vec/en/bert-base-uncased.h5py 
        prefilter: 500
        tolerate: 0

logger:
    appname: babi
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/babi/rule.log

