#app setting
APPNAME: END2END_DEMO
LANGUAGE: en


ner:
    TOKENIZER: ltp
    stopwords_path: data/cn_stopwords.txt
    cws_model_path: data/ltp_data/cws.model
    pos_model_path: data/ltp_data/pos.model
    ner_model_path: data/ltp_data/ner/*.ner
    ner_name_replace:
        Nh: PERSON
        Ni: ORG
        Ns: LOC
        person_name: PERSON
        company_name: ORG
        product_name: PRODUCT
        org_name: NORP
        location: LOC
        time: TIME
    regex:  
        EMAIL: '[a-zA-Z\d\.\-]+@[a-zA-Z\d\.\-]+\.[a-zA-Z\d]+'
        PHONE: '((\+\d{2,3})?1[34578]\d{9})|((\+\d{2,3})|0)\d{9,11}'
        ORDER: '\d{5,}'
        DATE: '(\d{2,4}年)?\d{1,2}月\d{1,2}[日号]|(\d{2,4}\-)?\d{1,2}\-\d{1,2}|(\d{2,4}\.)?\d{1,2}\.\d{1,2}'

model:
    use_gpu: False
    learning_rate: 0.001
    weight_decay: 0.0001
    epochs: 100
    saved_model: 'data/model.pt'

logger:
    LogLevel_Console:  10
    LogLevel_File: 0
    LogFile: /tmp/train.log
    LogFormat: '%(asctime)s | %(levelname)s: %(message)s'

