%YAML 1.2
---
#app setting

skill:
    name: cornell
    wrapper: GenerativeResponse

ner:
    tokenizer: spacy
    ner_name_replace:
    ner:
    keywords:
    regex:  

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

reader:
    wrapper: ReaderCornell
    train_data: /home/pzhu/data/dialog/cornell_corpus
    max_seq_len: 50

model:
    device: "cuda:0"
    dropout: 0.1
    decoder_hidden_layers: 4
    decoder_attention_heads: 3
    decoder_hidden_size: 3072
    learning_rate: 0.0001
    weight_decay: 0
    epochs: 100
    batch_size: 20
    num_workers: 1
    saved_model: 'data/cornell/model.pt'
    save_per_epoch: 1

reinforcement:
    learning_rate: 0.0001
    maxloop: 20
    discount: 0.95

logger:
    appname: cornell
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/cornell/train.log

