%YAML 1.2
---
#app setting

ner:
    tokenizer: spacy
    ner_name_replace:
    ner:
    keywords:
    regex:  

tokenizer:
    bert_model_name: /home/pzhu/data/bert/bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

reader:
    train_data: /home/pzhu/data/dialog/cornell_corpus
    max_seq_len: 50

model:
    skill_name: cornell
    device: "cuda:0"
    dropout: 0.2
    decoder_hidden_layers: 1
    decoder_attention_heads: 1
    decoder_hidden_size: 1024
    learning_rate: 0.001
    weight_decay: 0.00001
    epochs: 10000
    batch_size: 30
    num_workers: 1
    saved_model: 'data/cornell/model.pt'

reinforcement:
    learning_rate: 0.0001
    maxloop: 20
    discount: 0.95

logger:
    appname: cornell
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/cornell/train.log

