%YAML 1.2
---

#Config for elsa chatbot, interactive mode only

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

ner:
    tokenizer: spacy

backend:
    backend_type: shell
    url_rule: /robot/api/query
    methods:
        - POST
    port: 5001

topic_switch:
    strategy: queue # switch strategy, queue, current

timeout: 300 # seconds for session timeout

model:
    device: "cuda:0"
    max_seq_len: 20
    max_entity_types: 512

skills:
    cornell: 
        wrapper: GenerativeResponse
        beam_size: 5
        saved_model: 'data/cornell/cornell.pt'

