%YAML 1.2
---

#Config for elsa chatbot, interactive mode only

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

model:
    device: "cuda:0"
    max_seq_len: 20
    max_entity_types: 1024

skills:
    cornell: 
        wrapper: GenerativeResponse
        model_type: gru
        beam_size: 5
        saved_model: 'data/cornell/model_transformer.pt'

        #    babi: 
        #        wrapper: GoalResponse
        #        saved_model: 'data/babi/model.pt'
        #        template_file: data/babi/template.txt
        #        hook: 
        #            wrapper: Behaviors


logger:
    appname: elsa
    loglevel_console:  20
    loglevel_file: 0
    logfile: /tmp/elsa.log


