%YAML 1.2
---

#Config for elsa chatbot, interactive mode only

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

ner:
    tokenizer: spacy

backend:
    backend_type: shell

topic_switch:
    strategy: queue # switch strategy, queue, current

timeout: 300 # seconds for session timeout

model:
    device: "cuda:0"
    max_seq_len: 50
    max_entity_types: 512

backend:
    type: shell
    port: 5000

skills:
    cornell: 
        wrapper: GenerativeResponse
        model_type: transformer
        beam_size: 5
        saved_model: 'data/cornell/generative_5.pt'

        #babi:
        #wrapper: GoalResponse
        #saved_model: 'data/babi/model.pt'
        #dialogflow: data/babi/babi.xlsx


