%YAML 1.2
---

#Config for elsa chatbot, interactive mode only

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

ner:
    tokenizer: spacy

backend:
    backend_type: xmpp
    jid: elsa@ejabberd
    password: elsa123

topic_switch:
    strategy: queue # switch strategy, queue, current

timeout: 300 # seconds for session timeout

model:
    device: "cuda:0"
    max_seq_len: 20
    max_entity_types: 512

skills:
    cornell: 
        wrapper: RestResponse
        rest_url: http://192.168.1.112:5001/robot/api/query
        timeout: 3

