%YAML 1.2
---
#app setting

skill:
    name: cornell
    wrapper: GenerativeResponse

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1

reader:
    wrapper: ReaderCornell
    train_data: /data/omnia-010_1/data/cornell
    max_seq_len: 50
    flat_mode: True

model:
    device: "cuda:0"
    bert_model_name: "bert-base-uncased"
    encoder_hidden_layers: 4
    encoder_hidden_size: 768
    encoder_intermediate_size: 2048
    encoder_attention_heads: 8
    encoder_freeze: False
    dropout: 0.1
    decoder_hidden_layers: 4
    decoder_attention_heads: 8
    decoder_hidden_size: 2048
    learning_rate: 0.001
    weight_decay: 0
    momentum: 0.9
    optimizer: "bertadam"
    loss_scale: 128
    epochs: 100
    batch_size: 100
    num_workers: 1
    saved_model: '/data/omnia-010_1/data/generative_5.pt'
    #saved_model: 'data/cornell/model_transformer.pt'
    save_per_epoch: 100

reinforcement:
    learning_rate: 0.0001
    maxloop: 20
    discount: 0.95

logger:
    appname: cornell
    loglevel_console:  20
    loglevel_file: 0
    logfile: /tmp/cornell_train.log

