%YAML 1.2
---

ner:
    tokenizer: spacy

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

model:
    device: "cpu"
    max_seq_len: 20
    max_entity_types: 512

backend:
    type: shell
    port: 5000

skills:
    babi:
        wrapper: RuleResponse
        dialogflow: data/FAQs.xlsx
        w2v_word2idx: data/word2vec/en/bert-base-uncased.lookup 
        w2v_idx2vec: data/word2vec/en/bert-base-uncased.h5py 
        prefilter: 500
        tolerate: 0

    cornell: 
        wrapper: GenerativeResponse
        model_type: transformer
        beam_size: 5
        saved_model: 'data/cornell/cornell.pt'


