%YAML 1.2
---
#app setting
APPNAME: END2END_DEMO

response_template: 
    data: data/hr/template.txt
    cached_index: data/hr/template.index
    cached_vocab: data/hr/vocab_template.pkl
    vocab_size: 100000
    ngrams: 3


ner:
    LANGUAGE: en
    TOKENIZER: spacy
    w2v_word2idx: /home/pzhu/data/word2vec/en/word2idx_2000000.pp
    w2v_idx2vec: /home/pzhu/data/word2vec/en/weight_2000000.npy
    cached_vocab: data/hr/vocab_hr.pkl
    vocab_size: 100000
    cached_w2v: data/hr/w2v_hr.pkl
    vec_len: 300
    annoy_filter: 0.8
    stopwords_path: config/en_stopwords.txt
    entity_dict: data/hr/entity.dict
    max_entity_types: 17
    ner_name_replace:
        person_name: PERSON
        company_name: ORG
        product_name: PRODUCT
        org_name: NORP
        location: LOC
        time: TIME
    ner:
    keywords:
        USAGE: data/hr/entities/usage.txt
        USAGE_LETTER: data/hr/entities/usage_letter.txt
        USAGE_LETTER2: data/hr/entities/usage_letter2.txt
        USAGE_EMPLOYMENT: data/hr/entities/usage_employment.txt
        USAGE_WBS: data/hr/entities/usage_wbs.txt
        USAGE_LEAVE: data/hr/entities/usage_leave.txt
        USAGE_REASON: data/hr/entities/reason.txt
        LANGUAGE: data/hr/entities/language.txt
        LETTER_TYPE: data/hr/entities/letter_type.txt
        COUNTRY: data/hr/entities/country.txt
    regex:  
        EMAIL: '[a-zA-Z\d\.\-]+@[a-zA-Z\d\.\-]+(\.[a-zA-Z\d]{2,3}){1,2}'
        PASSPORT: 'G\d{8}'
        WBS: '(\d{1,3}x\d{1,3})|(a\d{6})'
        EID: '(?<=\s)[a-z]{1,10}(\.[a-z]{1,10}){1,3}(?=[\s\.])'
        DATE: '(\d{2,4}年)?\d{1,2}月\d{1,2}[日号]|(\d{2,4}\-)?\d{1,2}\-\d{1,2}|(\d{2,4}\.)?\d{1,2}\.\d{1,2}|(\d{2,4}\/)?\d{1,2}\/\d{1,4}'
        #NUMBER: '\d{1,5}(\,\d{1,5})?'


model:
    use_gpu: 1
    max_seq_len: 10
    max_entity_types: 17
    dropout: 0.5
    cnn_kernel_size: 5
    cnn_kernel_num: 64
    fc_response1: 50
    fc_response2: 10
    learning_rate: 0.0001
    weight_decay: 0.00001
    epochs: 100000
    batch_size: 1000
    saved_model: 'data/hr/model.pt'

logger:
    LogLevel_Console:  20
    LogLevel_File: 0
    LogFile: data/hr/train.log
    LogFormat: '%(asctime)s | %(levelname)s: %(message)s'

