#app setting
APPNAME: QA
LANGUAGE: en

data_path: '/home/pzhu/data/QA/quora_duplicate_questions.tsv'
data_cache: '/home/pzhu/data/QA/quora_duplicate_questions.pkl'

#w2v
w2v_word2idx: '/home/pzhu/data/word2vec/en/word2idx_2000000.pp'
w2v_idx2vec: '/home/pzhu/data/word2vec/en/weight_2000000.npy'
vec_len: 300

#vocab

#cached word2vec
cached_w2v: data/w2v_en.pkl
cached_vocab: data/vocab_en.pkl
vocab_size: 100000

#model
cnn_kernel_size: 5
cnn_kernel_num: 20
dropout: 0
batch_size: 4096
max_seq_len: 10
epochs: 3000
learning_rate: 0.0001
weight_decay: 0.00001
saved_model: data/quora_model.pt

#0 NOTSET, 10 DEBUG, 20 INFO, 30 WARNING, 40 ERROR, 50 CRITICAL
LogLevel_Console:  10
LogLevel_File: 0
LogFile: data/train.log
LogFormat: '%(asctime)s | %(levelname)s: %(message)s'


